//! 指令定义、操作数语义与栈效果契约。
//!
//! 本文件是 aluka 虚拟机的单一事实来源（由 isa-facts 反推生成）。
//! 严格遵循 AGENTS.md 规范：所有元数据查询使用穷尽 match，禁止任何兜底分支，
//! 确保在编译期阻断未登记或形状不匹配的指令。

/// 指令操作数语义分类（对应 11 种 OperandKind）。
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OperandKind {
    /// 不读操作数域
    None,
    /// 常量池索引
    ConstIdx,
    /// 24位内联无符号整数
    Int,
    /// 局部槽位索引
    Slot,
    /// 闭包上值索引
    UpvalueIdx,
    /// 模块级函数/类模板索引
    TemplateIdx,
    /// Try 表索引
    TryIdx,
    /// 有符号相对跳转字节偏移
    SignedOff,
    /// 参数或元素数量
    Count,
    /// 打包槽位与属性名 (slot<<16 | nameIdx)
    PackedSlotName,
    /// 打包实参数量与方法名 (numArgs<<16 | nameIdx)
    PackedCall,
}

/// 栈效果类别。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StackEffect {
    /// 确定的净入栈/出栈差值（pushes - pops）
    Fixed(i32),
    /// 依赖运行时条件或跳转是否发生的条件变化
    Conditional,
    /// 依赖操作数或实参/元素个数的动态变化
    Variable,
}

/// 106 条完整 ISA 字节码操作码。
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Op {
    /// [000] NOP (操作数: OperandNone)
    Nop = 0,
    /// [001] PUSH_UNDEFINED (操作数: OperandNone)
    PushUndefined = 1,
    /// [002] PUSH_NULL (操作数: OperandNone)
    PushNull = 2,
    /// [003] PUSH_TRUE (操作数: OperandNone)
    PushTrue = 3,
    /// [004] PUSH_FALSE (操作数: OperandNone)
    PushFalse = 4,
    /// [005] PUSH_CONST (操作数: OperandConstIdx)
    PushConst = 5,
    /// [006] PUSH_INT - 立即数：24位无符号小整数(0..16777215) (操作数: OperandInt)
    PushInt = 6,
    /// [007] PUSH_NEG_INT - 立即数：24位负整数，压入 -(A) (操作数: OperandInt)
    PushNegInt = 7,
    /// [008] POP (操作数: OperandNone)
    Pop = 8,
    /// [009] DUP (操作数: OperandNone)
    Dup = 9,
    /// [010] SWAP (操作数: OperandNone)
    Swap = 10,
    /// [011] LOAD_LOCAL (操作数: OperandSlot)
    LoadLocal = 11,
    /// [012] STORE_LOCAL (操作数: OperandSlot)
    StoreLocal = 12,
    /// [013] LOAD_GLOBAL (操作数: OperandConstIdx)
    LoadGlobal = 13,
    /// [014] STORE_GLOBAL (操作数: OperandConstIdx)
    StoreGlobal = 14,
    /// [015] LOAD_UPVALUE (操作数: OperandUpvalueIdx)
    LoadUpvalue = 15,
    /// [016] STORE_UPVALUE (操作数: OperandUpvalueIdx)
    StoreUpvalue = 16,
    /// [017] MAKE_CLOSURE (操作数: OperandTemplateIdx)
    MakeClosure = 17,
    /// [018] ADD (操作数: OperandNone)
    Add = 18,
    /// [019] SUB (操作数: OperandNone)
    Sub = 19,
    /// [020] MUL (操作数: OperandNone)
    Mul = 20,
    /// [021] DIV (操作数: OperandNone)
    Div = 21,
    /// [022] MOD (操作数: OperandNone)
    Mod = 22,
    /// [023] POW (操作数: OperandNone)
    Pow = 23,
    /// [024] BIT_AND (操作数: OperandNone)
    BitAnd = 24,
    /// [025] BIT_OR (操作数: OperandNone)
    BitOr = 25,
    /// [026] BIT_XOR (操作数: OperandNone)
    BitXor = 26,
    /// [027] SHL (操作数: OperandNone)
    Shl = 27,
    /// [028] SHR (操作数: OperandNone)
    Shr = 28,
    /// [029] USHR (操作数: OperandNone)
    UShr = 29,
    /// [030] NEG (操作数: OperandNone)
    Neg = 30,
    /// [031] NOT (操作数: OperandNone)
    Not = 31,
    /// [032] BIT_NOT (操作数: OperandNone)
    BitNot = 32,
    /// [033] TYPEOF (操作数: OperandNone)
    Typeof = 33,
    /// [034] EQ (操作数: OperandNone)
    Eq = 34,
    /// [035] STRICT_EQ (操作数: OperandNone)
    StrictEq = 35,
    /// [036] STRICT_NE (操作数: OperandNone)
    StrictNe = 36,
    /// [037] NE (操作数: OperandNone)
    Ne = 37,
    /// [038] LT (操作数: OperandNone)
    Lt = 38,
    /// [039] LE (操作数: OperandNone)
    Le = 39,
    /// [040] GT (操作数: OperandNone)
    Gt = 40,
    /// [041] GE (操作数: OperandNone)
    Ge = 41,
    /// [042] JMP - 相对跳转；跳转目标允许 target == len(code) (操作数: OperandSignedOff)
    Jmp = 42,
    /// [043] JMP_TRUE_POP (操作数: OperandSignedOff)
    JmpTruePop = 43,
    /// [044] JMP_FALSE_POP (操作数: OperandSignedOff)
    JmpFalsePop = 44,
    /// [045] JMP_TRUE_KEEP - 相对跳转；跳转目标允许 target == len(code) (操作数: OperandSignedOff)
    JmpTrueKeep = 45,
    /// [046] JMP_FALSE_KEEP - 相对跳转；跳转目标允许 target == len(code) (操作数: OperandSignedOff)
    JmpFalseKeep = 46,
    /// [047] JMP_NULLISH_KEEP - 相对跳转；跳转目标允许 target == len(code) (操作数: OperandSignedOff)
    JmpNullishKeep = 47,
    /// [048] OPTIONAL_JUMP (操作数: OperandSignedOff)
    OptionalJump = 48,
    /// [049] CALL (操作数: OperandCount)
    Call = 49,
    /// [050] CALL_METHOD - 打包调用：参数数量与方法名(numArgs<<16 | nameIdx) (操作数: OperandPackedCall)
    CallMethod = 50,
    /// [051] CALL_WITH_THIS (操作数: OperandCount)
    CallWithThis = 51,
    /// [052] CALL_WITH_THIS_ARGS (操作数: OperandNone)
    CallWithThisArgs = 52,
    /// [053] NEW (操作数: OperandCount)
    New = 53,
    /// [054] RETURN (操作数: OperandNone)
    Return = 54,
    /// [055] RETURN_UNDEF (操作数: OperandNone)
    ReturnUndef = 55,
    /// [056] NEW_OBJECT (操作数: OperandCount)
    NewObject = 56,
    /// [057] NEW_ARRAY (操作数: OperandCount)
    NewArray = 57,
    /// [058] GET_PROP (操作数: OperandConstIdx)
    GetProp = 58,
    /// [059] SET_PROP (操作数: OperandConstIdx)
    SetProp = 59,
    /// [060] SET_PROP_OBJ (操作数: OperandConstIdx)
    SetPropObj = 60,
    /// [061] SET_PROP_TOP (操作数: OperandConstIdx)
    SetPropTop = 61,
    /// [062] GET_ELEM (操作数: OperandNone)
    GetElem = 62,
    /// [063] SET_ELEM (操作数: OperandNone)
    SetElem = 63,
    /// [064] SET_ELEM_TOP (操作数: OperandNone)
    SetElemTop = 64,
    /// [065] DEL_PROP (操作数: OperandConstIdx)
    DelProp = 65,
    /// [066] DEL_ELEM (操作数: OperandNone)
    DelElem = 66,
    /// [067] SET_PROP_COMPUTED_OBJ (操作数: OperandNone)
    SetPropComputedObj = 67,
    /// [068] BUILD_ARRAY (操作数: OperandNone)
    BuildArray = 68,
    /// [069] ARRAY_PUSH (操作数: OperandNone)
    ArrayPush = 69,
    /// [070] ARRAY_SPREAD (操作数: OperandNone)
    ArraySpread = 70,
    /// [071] CALL_ARGS (操作数: OperandNone)
    CallArgs = 71,
    /// [072] CALL_METHOD_ARGS (操作数: OperandConstIdx)
    CallMethodArgs = 72,
    /// [073] NEW_ARGS (操作数: OperandNone)
    NewArgs = 73,
    /// [074] SPREAD_OBJECT (操作数: OperandNone)
    SpreadObject = 74,
    /// [075] UNARY_PLUS (操作数: OperandNone)
    UnaryPlus = 75,
    /// [076] TYPEOF_GLOBAL (操作数: OperandConstIdx)
    TypeofGlobal = 76,
    /// [077] TRY_ENTER (操作数: OperandTryIdx)
    TryEnter = 77,
    /// [078] TRY_EXIT (操作数: OperandTryIdx)
    TryExit = 78,
    /// [079] TRY_EXIT_FINALLY (操作数: OperandTryIdx)
    TryExitFinally = 79,
    /// [080] TRY_EXIT_JMP (操作数: OperandSignedOff)
    TryExitJmp = 80,
    /// [081] THROW (操作数: OperandNone)
    Throw = 81,
    /// [082] INSTANCEOF (操作数: OperandNone)
    Instanceof = 82,
    /// [083] IN (操作数: OperandNone)
    In = 83,
    /// [084] FOR_IN_NEXT - 遗留指令；VM中无对应dispatch分支 (操作数: OperandSignedOff)
    ForInNext = 84,
    /// [085] MAKE_CLASS (操作数: OperandTemplateIdx)
    MakeClass = 85,
    /// [086] GET_PROTO (操作数: OperandNone)
    GetProto = 86,
    /// [087] CALL_THIS (操作数: OperandCount)
    CallThis = 87,
    /// [088] CONSTRUCT_THIS (操作数: OperandCount)
    ConstructThis = 88,
    /// [089] CALL_THIS_ARGS (操作数: OperandNone)
    CallThisArgs = 89,
    /// [090] CONSTRUCT_THIS_ARGS (操作数: OperandNone)
    ConstructThisArgs = 90,
    /// [091] GET_ITERATOR (操作数: OperandNone)
    GetIterator = 91,
    /// [092] YIELD (操作数: OperandNone)
    Yield = 92,
    /// [093] GET_ASYNC_ITERATOR (操作数: OperandNone)
    GetAsyncIterator = 93,
    /// [094] AWAIT (操作数: OperandNone)
    Await = 94,
    /// [095] MAKE_REGEXP - 弹栈flags+pattern，生成RegExp对象 (操作数: OperandNone)
    MakeRegexp = 95,
    /// [096] SET_GETTER_OBJ (操作数: OperandConstIdx)
    SetGetterObj = 96,
    /// [097] SET_SETTER_OBJ (操作数: OperandConstIdx)
    SetSetterObj = 97,
    /// [098] SET_GETTER_COMPUTED_OBJ (操作数: OperandNone)
    SetGetterComputedObj = 98,
    /// [099] SET_SETTER_COMPUTED_OBJ (操作数: OperandNone)
    SetSetterComputedObj = 99,
    /// [100] GET_PROP_LOCAL - 超指令：打包局部槽位与属性名(slot<<16 | nameIdx) (操作数: OperandPackedSlotName)
    GetPropLocal = 100,
    /// [101] CLOSE_UPVALUES - 闭包作用域：关闭从指定槽位开始的捕获上值 (操作数: OperandSlot)
    CloseUpvalues = 101,
    /// [102] INC (操作数: OperandNone)
    Inc = 102,
    /// [103] DEC (操作数: OperandNone)
    Dec = 103,
    /// [104] ENUM_KEYS - 弹栈对象，压入原型链可枚举键数组 (操作数: OperandNone)
    EnumKeys = 104,
    /// [105] END - 代码结尾哨兵指令；不实际执行 (操作数: OperandNone)
    End = 105,
}

impl Op {
    /// 获取操作码的数值编码（0..105）。
    #[must_use]
    pub const fn opcode(self) -> u8 {
        self as u8
    }

    /// 从数值解码为操作码。
    #[must_use]
    pub fn from_opcode(byte: u8) -> Option<Self> {
        match byte {
            0 => Some(Op::Nop),
            1 => Some(Op::PushUndefined),
            2 => Some(Op::PushNull),
            3 => Some(Op::PushTrue),
            4 => Some(Op::PushFalse),
            5 => Some(Op::PushConst),
            6 => Some(Op::PushInt),
            7 => Some(Op::PushNegInt),
            8 => Some(Op::Pop),
            9 => Some(Op::Dup),
            10 => Some(Op::Swap),
            11 => Some(Op::LoadLocal),
            12 => Some(Op::StoreLocal),
            13 => Some(Op::LoadGlobal),
            14 => Some(Op::StoreGlobal),
            15 => Some(Op::LoadUpvalue),
            16 => Some(Op::StoreUpvalue),
            17 => Some(Op::MakeClosure),
            18 => Some(Op::Add),
            19 => Some(Op::Sub),
            20 => Some(Op::Mul),
            21 => Some(Op::Div),
            22 => Some(Op::Mod),
            23 => Some(Op::Pow),
            24 => Some(Op::BitAnd),
            25 => Some(Op::BitOr),
            26 => Some(Op::BitXor),
            27 => Some(Op::Shl),
            28 => Some(Op::Shr),
            29 => Some(Op::UShr),
            30 => Some(Op::Neg),
            31 => Some(Op::Not),
            32 => Some(Op::BitNot),
            33 => Some(Op::Typeof),
            34 => Some(Op::Eq),
            35 => Some(Op::StrictEq),
            36 => Some(Op::StrictNe),
            37 => Some(Op::Ne),
            38 => Some(Op::Lt),
            39 => Some(Op::Le),
            40 => Some(Op::Gt),
            41 => Some(Op::Ge),
            42 => Some(Op::Jmp),
            43 => Some(Op::JmpTruePop),
            44 => Some(Op::JmpFalsePop),
            45 => Some(Op::JmpTrueKeep),
            46 => Some(Op::JmpFalseKeep),
            47 => Some(Op::JmpNullishKeep),
            48 => Some(Op::OptionalJump),
            49 => Some(Op::Call),
            50 => Some(Op::CallMethod),
            51 => Some(Op::CallWithThis),
            52 => Some(Op::CallWithThisArgs),
            53 => Some(Op::New),
            54 => Some(Op::Return),
            55 => Some(Op::ReturnUndef),
            56 => Some(Op::NewObject),
            57 => Some(Op::NewArray),
            58 => Some(Op::GetProp),
            59 => Some(Op::SetProp),
            60 => Some(Op::SetPropObj),
            61 => Some(Op::SetPropTop),
            62 => Some(Op::GetElem),
            63 => Some(Op::SetElem),
            64 => Some(Op::SetElemTop),
            65 => Some(Op::DelProp),
            66 => Some(Op::DelElem),
            67 => Some(Op::SetPropComputedObj),
            68 => Some(Op::BuildArray),
            69 => Some(Op::ArrayPush),
            70 => Some(Op::ArraySpread),
            71 => Some(Op::CallArgs),
            72 => Some(Op::CallMethodArgs),
            73 => Some(Op::NewArgs),
            74 => Some(Op::SpreadObject),
            75 => Some(Op::UnaryPlus),
            76 => Some(Op::TypeofGlobal),
            77 => Some(Op::TryEnter),
            78 => Some(Op::TryExit),
            79 => Some(Op::TryExitFinally),
            80 => Some(Op::TryExitJmp),
            81 => Some(Op::Throw),
            82 => Some(Op::Instanceof),
            83 => Some(Op::In),
            84 => Some(Op::ForInNext),
            85 => Some(Op::MakeClass),
            86 => Some(Op::GetProto),
            87 => Some(Op::CallThis),
            88 => Some(Op::ConstructThis),
            89 => Some(Op::CallThisArgs),
            90 => Some(Op::ConstructThisArgs),
            91 => Some(Op::GetIterator),
            92 => Some(Op::Yield),
            93 => Some(Op::GetAsyncIterator),
            94 => Some(Op::Await),
            95 => Some(Op::MakeRegexp),
            96 => Some(Op::SetGetterObj),
            97 => Some(Op::SetSetterObj),
            98 => Some(Op::SetGetterComputedObj),
            99 => Some(Op::SetSetterComputedObj),
            100 => Some(Op::GetPropLocal),
            101 => Some(Op::CloseUpvalues),
            102 => Some(Op::Inc),
            103 => Some(Op::Dec),
            104 => Some(Op::EnumKeys),
            105 => Some(Op::End),
            _ => None,
        }
    }

    /// 规范大写指令名。
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Op::Nop => "NOP",
            Op::PushUndefined => "PUSH_UNDEFINED",
            Op::PushNull => "PUSH_NULL",
            Op::PushTrue => "PUSH_TRUE",
            Op::PushFalse => "PUSH_FALSE",
            Op::PushConst => "PUSH_CONST",
            Op::PushInt => "PUSH_INT",
            Op::PushNegInt => "PUSH_NEG_INT",
            Op::Pop => "POP",
            Op::Dup => "DUP",
            Op::Swap => "SWAP",
            Op::LoadLocal => "LOAD_LOCAL",
            Op::StoreLocal => "STORE_LOCAL",
            Op::LoadGlobal => "LOAD_GLOBAL",
            Op::StoreGlobal => "STORE_GLOBAL",
            Op::LoadUpvalue => "LOAD_UPVALUE",
            Op::StoreUpvalue => "STORE_UPVALUE",
            Op::MakeClosure => "MAKE_CLOSURE",
            Op::Add => "ADD",
            Op::Sub => "SUB",
            Op::Mul => "MUL",
            Op::Div => "DIV",
            Op::Mod => "MOD",
            Op::Pow => "POW",
            Op::BitAnd => "BIT_AND",
            Op::BitOr => "BIT_OR",
            Op::BitXor => "BIT_XOR",
            Op::Shl => "SHL",
            Op::Shr => "SHR",
            Op::UShr => "USHR",
            Op::Neg => "NEG",
            Op::Not => "NOT",
            Op::BitNot => "BIT_NOT",
            Op::Typeof => "TYPEOF",
            Op::Eq => "EQ",
            Op::StrictEq => "STRICT_EQ",
            Op::StrictNe => "STRICT_NE",
            Op::Ne => "NE",
            Op::Lt => "LT",
            Op::Le => "LE",
            Op::Gt => "GT",
            Op::Ge => "GE",
            Op::Jmp => "JMP",
            Op::JmpTruePop => "JMP_TRUE_POP",
            Op::JmpFalsePop => "JMP_FALSE_POP",
            Op::JmpTrueKeep => "JMP_TRUE_KEEP",
            Op::JmpFalseKeep => "JMP_FALSE_KEEP",
            Op::JmpNullishKeep => "JMP_NULLISH_KEEP",
            Op::OptionalJump => "OPTIONAL_JUMP",
            Op::Call => "CALL",
            Op::CallMethod => "CALL_METHOD",
            Op::CallWithThis => "CALL_WITH_THIS",
            Op::CallWithThisArgs => "CALL_WITH_THIS_ARGS",
            Op::New => "NEW",
            Op::Return => "RETURN",
            Op::ReturnUndef => "RETURN_UNDEF",
            Op::NewObject => "NEW_OBJECT",
            Op::NewArray => "NEW_ARRAY",
            Op::GetProp => "GET_PROP",
            Op::SetProp => "SET_PROP",
            Op::SetPropObj => "SET_PROP_OBJ",
            Op::SetPropTop => "SET_PROP_TOP",
            Op::GetElem => "GET_ELEM",
            Op::SetElem => "SET_ELEM",
            Op::SetElemTop => "SET_ELEM_TOP",
            Op::DelProp => "DEL_PROP",
            Op::DelElem => "DEL_ELEM",
            Op::SetPropComputedObj => "SET_PROP_COMPUTED_OBJ",
            Op::BuildArray => "BUILD_ARRAY",
            Op::ArrayPush => "ARRAY_PUSH",
            Op::ArraySpread => "ARRAY_SPREAD",
            Op::CallArgs => "CALL_ARGS",
            Op::CallMethodArgs => "CALL_METHOD_ARGS",
            Op::NewArgs => "NEW_ARGS",
            Op::SpreadObject => "SPREAD_OBJECT",
            Op::UnaryPlus => "UNARY_PLUS",
            Op::TypeofGlobal => "TYPEOF_GLOBAL",
            Op::TryEnter => "TRY_ENTER",
            Op::TryExit => "TRY_EXIT",
            Op::TryExitFinally => "TRY_EXIT_FINALLY",
            Op::TryExitJmp => "TRY_EXIT_JMP",
            Op::Throw => "THROW",
            Op::Instanceof => "INSTANCEOF",
            Op::In => "IN",
            Op::ForInNext => "FOR_IN_NEXT",
            Op::MakeClass => "MAKE_CLASS",
            Op::GetProto => "GET_PROTO",
            Op::CallThis => "CALL_THIS",
            Op::ConstructThis => "CONSTRUCT_THIS",
            Op::CallThisArgs => "CALL_THIS_ARGS",
            Op::ConstructThisArgs => "CONSTRUCT_THIS_ARGS",
            Op::GetIterator => "GET_ITERATOR",
            Op::Yield => "YIELD",
            Op::GetAsyncIterator => "GET_ASYNC_ITERATOR",
            Op::Await => "AWAIT",
            Op::MakeRegexp => "MAKE_REGEXP",
            Op::SetGetterObj => "SET_GETTER_OBJ",
            Op::SetSetterObj => "SET_SETTER_OBJ",
            Op::SetGetterComputedObj => "SET_GETTER_COMPUTED_OBJ",
            Op::SetSetterComputedObj => "SET_SETTER_COMPUTED_OBJ",
            Op::GetPropLocal => "GET_PROP_LOCAL",
            Op::CloseUpvalues => "CLOSE_UPVALUES",
            Op::Inc => "INC",
            Op::Dec => "DEC",
            Op::EnumKeys => "ENUM_KEYS",
            Op::End => "END",
        }
    }

    /// 操作数语义类别。
    #[must_use]
    pub const fn operand_kind(self) -> OperandKind {
        match self {
            Op::Nop => OperandKind::None,
            Op::PushUndefined => OperandKind::None,
            Op::PushNull => OperandKind::None,
            Op::PushTrue => OperandKind::None,
            Op::PushFalse => OperandKind::None,
            Op::PushConst => OperandKind::ConstIdx,
            Op::PushInt => OperandKind::Int,
            Op::PushNegInt => OperandKind::Int,
            Op::Pop => OperandKind::None,
            Op::Dup => OperandKind::None,
            Op::Swap => OperandKind::None,
            Op::LoadLocal => OperandKind::Slot,
            Op::StoreLocal => OperandKind::Slot,
            Op::LoadGlobal => OperandKind::ConstIdx,
            Op::StoreGlobal => OperandKind::ConstIdx,
            Op::LoadUpvalue => OperandKind::UpvalueIdx,
            Op::StoreUpvalue => OperandKind::UpvalueIdx,
            Op::MakeClosure => OperandKind::TemplateIdx,
            Op::Add => OperandKind::None,
            Op::Sub => OperandKind::None,
            Op::Mul => OperandKind::None,
            Op::Div => OperandKind::None,
            Op::Mod => OperandKind::None,
            Op::Pow => OperandKind::None,
            Op::BitAnd => OperandKind::None,
            Op::BitOr => OperandKind::None,
            Op::BitXor => OperandKind::None,
            Op::Shl => OperandKind::None,
            Op::Shr => OperandKind::None,
            Op::UShr => OperandKind::None,
            Op::Neg => OperandKind::None,
            Op::Not => OperandKind::None,
            Op::BitNot => OperandKind::None,
            Op::Typeof => OperandKind::None,
            Op::Eq => OperandKind::None,
            Op::StrictEq => OperandKind::None,
            Op::StrictNe => OperandKind::None,
            Op::Ne => OperandKind::None,
            Op::Lt => OperandKind::None,
            Op::Le => OperandKind::None,
            Op::Gt => OperandKind::None,
            Op::Ge => OperandKind::None,
            Op::Jmp => OperandKind::SignedOff,
            Op::JmpTruePop => OperandKind::SignedOff,
            Op::JmpFalsePop => OperandKind::SignedOff,
            Op::JmpTrueKeep => OperandKind::SignedOff,
            Op::JmpFalseKeep => OperandKind::SignedOff,
            Op::JmpNullishKeep => OperandKind::SignedOff,
            Op::OptionalJump => OperandKind::SignedOff,
            Op::Call => OperandKind::Count,
            Op::CallMethod => OperandKind::PackedCall,
            Op::CallWithThis => OperandKind::Count,
            Op::CallWithThisArgs => OperandKind::None,
            Op::New => OperandKind::Count,
            Op::Return => OperandKind::None,
            Op::ReturnUndef => OperandKind::None,
            Op::NewObject => OperandKind::Count,
            Op::NewArray => OperandKind::Count,
            Op::GetProp => OperandKind::ConstIdx,
            Op::SetProp => OperandKind::ConstIdx,
            Op::SetPropObj => OperandKind::ConstIdx,
            Op::SetPropTop => OperandKind::ConstIdx,
            Op::GetElem => OperandKind::None,
            Op::SetElem => OperandKind::None,
            Op::SetElemTop => OperandKind::None,
            Op::DelProp => OperandKind::ConstIdx,
            Op::DelElem => OperandKind::None,
            Op::SetPropComputedObj => OperandKind::None,
            Op::BuildArray => OperandKind::None,
            Op::ArrayPush => OperandKind::None,
            Op::ArraySpread => OperandKind::None,
            Op::CallArgs => OperandKind::None,
            Op::CallMethodArgs => OperandKind::ConstIdx,
            Op::NewArgs => OperandKind::None,
            Op::SpreadObject => OperandKind::None,
            Op::UnaryPlus => OperandKind::None,
            Op::TypeofGlobal => OperandKind::ConstIdx,
            Op::TryEnter => OperandKind::TryIdx,
            Op::TryExit => OperandKind::TryIdx,
            Op::TryExitFinally => OperandKind::TryIdx,
            Op::TryExitJmp => OperandKind::SignedOff,
            Op::Throw => OperandKind::None,
            Op::Instanceof => OperandKind::None,
            Op::In => OperandKind::None,
            Op::ForInNext => OperandKind::SignedOff,
            Op::MakeClass => OperandKind::TemplateIdx,
            Op::GetProto => OperandKind::None,
            Op::CallThis => OperandKind::Count,
            Op::ConstructThis => OperandKind::Count,
            Op::CallThisArgs => OperandKind::None,
            Op::ConstructThisArgs => OperandKind::None,
            Op::GetIterator => OperandKind::None,
            Op::Yield => OperandKind::None,
            Op::GetAsyncIterator => OperandKind::None,
            Op::Await => OperandKind::None,
            Op::MakeRegexp => OperandKind::None,
            Op::SetGetterObj => OperandKind::ConstIdx,
            Op::SetSetterObj => OperandKind::ConstIdx,
            Op::SetGetterComputedObj => OperandKind::None,
            Op::SetSetterComputedObj => OperandKind::None,
            Op::GetPropLocal => OperandKind::PackedSlotName,
            Op::CloseUpvalues => OperandKind::Slot,
            Op::Inc => OperandKind::None,
            Op::Dec => OperandKind::None,
            Op::EnumKeys => OperandKind::None,
            Op::End => OperandKind::None,
        }
    }

    /// 是否含有 3 字节有效操作数。
    #[must_use]
    pub fn has_operand(self) -> bool {
        !matches!(self.operand_kind(), OperandKind::None)
    }

    /// 该指令对操作数栈深度的静态净影响（压入数 − 弹出数）。
    ///
    /// 对于条件跳转短路（如 JMP_TRUE_KEEP）或动态操作数指令（如 CALL），
    /// 该静态函数返回 0。如需更精细类型请调用 Self::stack_effect_detailed。
    #[must_use]
    pub fn stack_effect(self) -> i32 {
        match self {
            Op::Nop => 0,
            Op::PushUndefined => 1,
            Op::PushNull => 1,
            Op::PushTrue => 1,
            Op::PushFalse => 1,
            Op::PushConst => 1,
            Op::PushInt => 1,
            Op::PushNegInt => 1,
            Op::Pop => -1,
            Op::Dup => 1,
            Op::Swap => 0,
            Op::LoadLocal => 1,
            Op::StoreLocal => -1,
            Op::LoadGlobal => 1,
            Op::StoreGlobal => -1,
            Op::LoadUpvalue => 1,
            Op::StoreUpvalue => -1,
            Op::MakeClosure => 1,
            Op::Add => -1,
            Op::Sub => -1,
            Op::Mul => -1,
            Op::Div => -1,
            Op::Mod => -1,
            Op::Pow => -1,
            Op::BitAnd => -1,
            Op::BitOr => -1,
            Op::BitXor => -1,
            Op::Shl => -1,
            Op::Shr => -1,
            Op::UShr => -1,
            Op::Neg => 0,
            Op::Not => 0,
            Op::BitNot => 0,
            Op::Typeof => 0,
            Op::Eq => -1,
            Op::StrictEq => -1,
            Op::StrictNe => -1,
            Op::Ne => -1,
            Op::Lt => -1,
            Op::Le => -1,
            Op::Gt => -1,
            Op::Ge => -1,
            Op::Jmp => 0,
            Op::JmpTruePop => -1,
            Op::JmpFalsePop => -1,
            Op::JmpTrueKeep => 0,
            Op::JmpFalseKeep => 0,
            Op::JmpNullishKeep => 0,
            Op::OptionalJump => 0,
            Op::Call => 0,
            Op::CallMethod => 0,
            Op::CallWithThis => 0,
            Op::CallWithThisArgs => 0,
            Op::New => 0,
            Op::Return => -1,
            Op::ReturnUndef => 0,
            Op::NewObject => 0,
            Op::NewArray => 0,
            Op::GetProp => 0,
            Op::SetProp => -1,
            Op::SetPropObj => -1,
            Op::SetPropTop => -2,
            Op::GetElem => -1,
            Op::SetElem => -2,
            Op::SetElemTop => -3,
            Op::DelProp => 0,
            Op::DelElem => -1,
            Op::SetPropComputedObj => -2,
            Op::BuildArray => 1,
            Op::ArrayPush => -1,
            Op::ArraySpread => -1,
            Op::CallArgs => 0,
            Op::CallMethodArgs => 0,
            Op::NewArgs => 0,
            Op::SpreadObject => -1,
            Op::UnaryPlus => 0,
            Op::TypeofGlobal => 1,
            Op::TryEnter => 0,
            Op::TryExit => 0,
            Op::TryExitFinally => 0,
            Op::TryExitJmp => 0,
            Op::Throw => -1,
            Op::Instanceof => -1,
            Op::In => -1,
            Op::ForInNext => 0,
            Op::MakeClass => 0,
            Op::GetProto => 0,
            Op::CallThis => 0,
            Op::ConstructThis => 0,
            Op::CallThisArgs => 0,
            Op::ConstructThisArgs => 0,
            Op::GetIterator => 0,
            Op::Yield => -1,
            Op::GetAsyncIterator => 0,
            Op::Await => 0,
            Op::MakeRegexp => -1,
            Op::SetGetterObj => -1,
            Op::SetSetterObj => -1,
            Op::SetGetterComputedObj => -2,
            Op::SetSetterComputedObj => -2,
            Op::GetPropLocal => 1,
            Op::CloseUpvalues => 0,
            Op::Inc => 0,
            Op::Dec => 0,
            Op::EnumKeys => 0,
            Op::End => 0,
        }
    }

    /// 详细结构化栈效果。
    #[must_use]
    pub fn stack_effect_detailed(self) -> StackEffect {
        match self {
            Op::Nop => StackEffect::Fixed(0),
            Op::PushUndefined => StackEffect::Fixed(1),
            Op::PushNull => StackEffect::Fixed(1),
            Op::PushTrue => StackEffect::Fixed(1),
            Op::PushFalse => StackEffect::Fixed(1),
            Op::PushConst => StackEffect::Fixed(1),
            Op::PushInt => StackEffect::Fixed(1),
            Op::PushNegInt => StackEffect::Fixed(1),
            Op::Pop => StackEffect::Fixed(-1),
            Op::Dup => StackEffect::Fixed(1),
            Op::Swap => StackEffect::Fixed(0),
            Op::LoadLocal => StackEffect::Fixed(1),
            Op::StoreLocal => StackEffect::Fixed(-1),
            Op::LoadGlobal => StackEffect::Fixed(1),
            Op::StoreGlobal => StackEffect::Fixed(-1),
            Op::LoadUpvalue => StackEffect::Fixed(1),
            Op::StoreUpvalue => StackEffect::Fixed(-1),
            Op::MakeClosure => StackEffect::Fixed(1),
            Op::Add => StackEffect::Fixed(-1),
            Op::Sub => StackEffect::Fixed(-1),
            Op::Mul => StackEffect::Fixed(-1),
            Op::Div => StackEffect::Fixed(-1),
            Op::Mod => StackEffect::Fixed(-1),
            Op::Pow => StackEffect::Fixed(-1),
            Op::BitAnd => StackEffect::Fixed(-1),
            Op::BitOr => StackEffect::Fixed(-1),
            Op::BitXor => StackEffect::Fixed(-1),
            Op::Shl => StackEffect::Fixed(-1),
            Op::Shr => StackEffect::Fixed(-1),
            Op::UShr => StackEffect::Fixed(-1),
            Op::Neg => StackEffect::Fixed(0),
            Op::Not => StackEffect::Fixed(0),
            Op::BitNot => StackEffect::Fixed(0),
            Op::Typeof => StackEffect::Fixed(0),
            Op::Eq => StackEffect::Fixed(-1),
            Op::StrictEq => StackEffect::Fixed(-1),
            Op::StrictNe => StackEffect::Fixed(-1),
            Op::Ne => StackEffect::Fixed(-1),
            Op::Lt => StackEffect::Fixed(-1),
            Op::Le => StackEffect::Fixed(-1),
            Op::Gt => StackEffect::Fixed(-1),
            Op::Ge => StackEffect::Fixed(-1),
            Op::Jmp => StackEffect::Fixed(0),
            Op::JmpTruePop => StackEffect::Fixed(-1),
            Op::JmpFalsePop => StackEffect::Fixed(-1),
            Op::JmpTrueKeep => StackEffect::Conditional,
            Op::JmpFalseKeep => StackEffect::Conditional,
            Op::JmpNullishKeep => StackEffect::Conditional,
            Op::OptionalJump => StackEffect::Conditional,
            Op::Call => StackEffect::Variable,
            Op::CallMethod => StackEffect::Variable,
            Op::CallWithThis => StackEffect::Variable,
            Op::CallWithThisArgs => StackEffect::Variable,
            Op::New => StackEffect::Variable,
            Op::Return => StackEffect::Fixed(-1),
            Op::ReturnUndef => StackEffect::Fixed(0),
            Op::NewObject => StackEffect::Variable,
            Op::NewArray => StackEffect::Variable,
            Op::GetProp => StackEffect::Fixed(0),
            Op::SetProp => StackEffect::Fixed(-1),
            Op::SetPropObj => StackEffect::Fixed(-1),
            Op::SetPropTop => StackEffect::Fixed(-2),
            Op::GetElem => StackEffect::Fixed(-1),
            Op::SetElem => StackEffect::Fixed(-2),
            Op::SetElemTop => StackEffect::Fixed(-3),
            Op::DelProp => StackEffect::Fixed(0),
            Op::DelElem => StackEffect::Fixed(-1),
            Op::SetPropComputedObj => StackEffect::Fixed(-2),
            Op::BuildArray => StackEffect::Fixed(1),
            Op::ArrayPush => StackEffect::Fixed(-1),
            Op::ArraySpread => StackEffect::Fixed(-1),
            Op::CallArgs => StackEffect::Variable,
            Op::CallMethodArgs => StackEffect::Variable,
            Op::NewArgs => StackEffect::Variable,
            Op::SpreadObject => StackEffect::Fixed(-1),
            Op::UnaryPlus => StackEffect::Fixed(0),
            Op::TypeofGlobal => StackEffect::Fixed(1),
            Op::TryEnter => StackEffect::Fixed(0),
            Op::TryExit => StackEffect::Fixed(0),
            Op::TryExitFinally => StackEffect::Fixed(0),
            Op::TryExitJmp => StackEffect::Fixed(0),
            Op::Throw => StackEffect::Fixed(-1),
            Op::Instanceof => StackEffect::Fixed(-1),
            Op::In => StackEffect::Fixed(-1),
            Op::ForInNext => StackEffect::Variable,
            Op::MakeClass => StackEffect::Variable,
            Op::GetProto => StackEffect::Fixed(0),
            Op::CallThis => StackEffect::Variable,
            Op::ConstructThis => StackEffect::Variable,
            Op::CallThisArgs => StackEffect::Variable,
            Op::ConstructThisArgs => StackEffect::Variable,
            Op::GetIterator => StackEffect::Fixed(0),
            Op::Yield => StackEffect::Fixed(-1),
            Op::GetAsyncIterator => StackEffect::Fixed(0),
            Op::Await => StackEffect::Fixed(0),
            Op::MakeRegexp => StackEffect::Fixed(-1),
            Op::SetGetterObj => StackEffect::Fixed(-1),
            Op::SetSetterObj => StackEffect::Fixed(-1),
            Op::SetGetterComputedObj => StackEffect::Fixed(-2),
            Op::SetSetterComputedObj => StackEffect::Fixed(-2),
            Op::GetPropLocal => StackEffect::Fixed(1),
            Op::CloseUpvalues => StackEffect::Fixed(0),
            Op::Inc => StackEffect::Fixed(0),
            Op::Dec => StackEffect::Fixed(0),
            Op::EnumKeys => StackEffect::Fixed(0),
            Op::End => StackEffect::Fixed(0),
        }
    }

    /// 指令弹出的操作数个数。
    #[must_use]
    pub const fn pops(self) -> u8 {
        match self {
            Op::Nop => 0,
            Op::PushUndefined => 0,
            Op::PushNull => 0,
            Op::PushTrue => 0,
            Op::PushFalse => 0,
            Op::PushConst => 0,
            Op::PushInt => 0,
            Op::PushNegInt => 0,
            Op::Pop => 1,
            Op::Dup => 0,
            Op::Swap => 2,
            Op::LoadLocal => 0,
            Op::StoreLocal => 1,
            Op::LoadGlobal => 0,
            Op::StoreGlobal => 1,
            Op::LoadUpvalue => 0,
            Op::StoreUpvalue => 1,
            Op::MakeClosure => 0,
            Op::Add => 2,
            Op::Sub => 2,
            Op::Mul => 2,
            Op::Div => 2,
            Op::Mod => 2,
            Op::Pow => 2,
            Op::BitAnd => 2,
            Op::BitOr => 2,
            Op::BitXor => 2,
            Op::Shl => 2,
            Op::Shr => 2,
            Op::UShr => 2,
            Op::Neg => 1,
            Op::Not => 1,
            Op::BitNot => 1,
            Op::Typeof => 1,
            Op::Eq => 2,
            Op::StrictEq => 2,
            Op::StrictNe => 2,
            Op::Ne => 2,
            Op::Lt => 2,
            Op::Le => 2,
            Op::Gt => 2,
            Op::Ge => 2,
            Op::Jmp => 0,
            Op::JmpTruePop => 1,
            Op::JmpFalsePop => 1,
            Op::JmpTrueKeep => 0,
            Op::JmpFalseKeep => 0,
            Op::JmpNullishKeep => 0,
            Op::OptionalJump => 0,
            Op::Call => 0,
            Op::CallMethod => 0,
            Op::CallWithThis => 0,
            Op::CallWithThisArgs => 0,
            Op::New => 0,
            Op::Return => 1,
            Op::ReturnUndef => 0,
            Op::NewObject => 0,
            Op::NewArray => 0,
            Op::GetProp => 1,
            Op::SetProp => 2,
            Op::SetPropObj => 1,
            Op::SetPropTop => 2,
            Op::GetElem => 2,
            Op::SetElem => 3,
            Op::SetElemTop => 3,
            Op::DelProp => 1,
            Op::DelElem => 2,
            Op::SetPropComputedObj => 2,
            Op::BuildArray => 0,
            Op::ArrayPush => 1,
            Op::ArraySpread => 1,
            Op::CallArgs => 0,
            Op::CallMethodArgs => 0,
            Op::NewArgs => 0,
            Op::SpreadObject => 1,
            Op::UnaryPlus => 1,
            Op::TypeofGlobal => 0,
            Op::TryEnter => 0,
            Op::TryExit => 0,
            Op::TryExitFinally => 0,
            Op::TryExitJmp => 0,
            Op::Throw => 1,
            Op::Instanceof => 2,
            Op::In => 2,
            Op::ForInNext => 0,
            Op::MakeClass => 0,
            Op::GetProto => 1,
            Op::CallThis => 0,
            Op::ConstructThis => 0,
            Op::CallThisArgs => 0,
            Op::ConstructThisArgs => 0,
            Op::GetIterator => 1,
            Op::Yield => 1,
            Op::GetAsyncIterator => 1,
            Op::Await => 1,
            Op::MakeRegexp => 2,
            Op::SetGetterObj => 1,
            Op::SetSetterObj => 1,
            Op::SetGetterComputedObj => 2,
            Op::SetSetterComputedObj => 2,
            Op::GetPropLocal => 0,
            Op::CloseUpvalues => 0,
            Op::Inc => 1,
            Op::Dec => 1,
            Op::EnumKeys => 1,
            Op::End => 0,
        }
    }

    /// 指令压入的操作数个数。
    #[must_use]
    pub const fn pushes(self) -> u8 {
        match self {
            Op::Nop => 0,
            Op::PushUndefined => 1,
            Op::PushNull => 1,
            Op::PushTrue => 1,
            Op::PushFalse => 1,
            Op::PushConst => 1,
            Op::PushInt => 1,
            Op::PushNegInt => 1,
            Op::Pop => 0,
            Op::Dup => 1,
            Op::Swap => 2,
            Op::LoadLocal => 1,
            Op::StoreLocal => 0,
            Op::LoadGlobal => 1,
            Op::StoreGlobal => 0,
            Op::LoadUpvalue => 1,
            Op::StoreUpvalue => 0,
            Op::MakeClosure => 1,
            Op::Add => 1,
            Op::Sub => 1,
            Op::Mul => 1,
            Op::Div => 1,
            Op::Mod => 1,
            Op::Pow => 1,
            Op::BitAnd => 1,
            Op::BitOr => 1,
            Op::BitXor => 1,
            Op::Shl => 1,
            Op::Shr => 1,
            Op::UShr => 1,
            Op::Neg => 1,
            Op::Not => 1,
            Op::BitNot => 1,
            Op::Typeof => 1,
            Op::Eq => 1,
            Op::StrictEq => 1,
            Op::StrictNe => 1,
            Op::Ne => 1,
            Op::Lt => 1,
            Op::Le => 1,
            Op::Gt => 1,
            Op::Ge => 1,
            Op::Jmp => 0,
            Op::JmpTruePop => 0,
            Op::JmpFalsePop => 0,
            Op::JmpTrueKeep => 0,
            Op::JmpFalseKeep => 0,
            Op::JmpNullishKeep => 0,
            Op::OptionalJump => 0,
            Op::Call => 1,
            Op::CallMethod => 1,
            Op::CallWithThis => 1,
            Op::CallWithThisArgs => 1,
            Op::New => 1,
            Op::Return => 0,
            Op::ReturnUndef => 0,
            Op::NewObject => 1,
            Op::NewArray => 1,
            Op::GetProp => 1,
            Op::SetProp => 1,
            Op::SetPropObj => 0,
            Op::SetPropTop => 0,
            Op::GetElem => 1,
            Op::SetElem => 1,
            Op::SetElemTop => 0,
            Op::DelProp => 1,
            Op::DelElem => 1,
            Op::SetPropComputedObj => 0,
            Op::BuildArray => 1,
            Op::ArrayPush => 0,
            Op::ArraySpread => 0,
            Op::CallArgs => 1,
            Op::CallMethodArgs => 1,
            Op::NewArgs => 1,
            Op::SpreadObject => 0,
            Op::UnaryPlus => 1,
            Op::TypeofGlobal => 1,
            Op::TryEnter => 0,
            Op::TryExit => 0,
            Op::TryExitFinally => 0,
            Op::TryExitJmp => 0,
            Op::Throw => 0,
            Op::Instanceof => 1,
            Op::In => 1,
            Op::ForInNext => 0,
            Op::MakeClass => 1,
            Op::GetProto => 1,
            Op::CallThis => 1,
            Op::ConstructThis => 1,
            Op::CallThisArgs => 1,
            Op::ConstructThisArgs => 1,
            Op::GetIterator => 1,
            Op::Yield => 0,
            Op::GetAsyncIterator => 1,
            Op::Await => 1,
            Op::MakeRegexp => 1,
            Op::SetGetterObj => 0,
            Op::SetSetterObj => 0,
            Op::SetGetterComputedObj => 0,
            Op::SetSetterComputedObj => 0,
            Op::GetPropLocal => 1,
            Op::CloseUpvalues => 0,
            Op::Inc => 1,
            Op::Dec => 1,
            Op::EnumKeys => 1,
            Op::End => 0,
        }
    }

    /// 是否为纯字面量压栈（无副作用，可安全做死代码消除）。
    #[must_use]
    pub const fn is_pure_push(self) -> bool {
        match self {
            Op::Nop => false,
            Op::PushUndefined => true,
            Op::PushNull => true,
            Op::PushTrue => true,
            Op::PushFalse => true,
            Op::PushConst => true,
            Op::PushInt => true,
            Op::PushNegInt => true,
            Op::Pop => false,
            Op::Dup => false,
            Op::Swap => false,
            Op::LoadLocal => false,
            Op::StoreLocal => false,
            Op::LoadGlobal => false,
            Op::StoreGlobal => false,
            Op::LoadUpvalue => false,
            Op::StoreUpvalue => false,
            Op::MakeClosure => false,
            Op::Add => false,
            Op::Sub => false,
            Op::Mul => false,
            Op::Div => false,
            Op::Mod => false,
            Op::Pow => false,
            Op::BitAnd => false,
            Op::BitOr => false,
            Op::BitXor => false,
            Op::Shl => false,
            Op::Shr => false,
            Op::UShr => false,
            Op::Neg => false,
            Op::Not => false,
            Op::BitNot => false,
            Op::Typeof => false,
            Op::Eq => false,
            Op::StrictEq => false,
            Op::StrictNe => false,
            Op::Ne => false,
            Op::Lt => false,
            Op::Le => false,
            Op::Gt => false,
            Op::Ge => false,
            Op::Jmp => false,
            Op::JmpTruePop => false,
            Op::JmpFalsePop => false,
            Op::JmpTrueKeep => false,
            Op::JmpFalseKeep => false,
            Op::JmpNullishKeep => false,
            Op::OptionalJump => false,
            Op::Call => false,
            Op::CallMethod => false,
            Op::CallWithThis => false,
            Op::CallWithThisArgs => false,
            Op::New => false,
            Op::Return => false,
            Op::ReturnUndef => false,
            Op::NewObject => false,
            Op::NewArray => false,
            Op::GetProp => false,
            Op::SetProp => false,
            Op::SetPropObj => false,
            Op::SetPropTop => false,
            Op::GetElem => false,
            Op::SetElem => false,
            Op::SetElemTop => false,
            Op::DelProp => false,
            Op::DelElem => false,
            Op::SetPropComputedObj => false,
            Op::BuildArray => false,
            Op::ArrayPush => false,
            Op::ArraySpread => false,
            Op::CallArgs => false,
            Op::CallMethodArgs => false,
            Op::NewArgs => false,
            Op::SpreadObject => false,
            Op::UnaryPlus => false,
            Op::TypeofGlobal => false,
            Op::TryEnter => false,
            Op::TryExit => false,
            Op::TryExitFinally => false,
            Op::TryExitJmp => false,
            Op::Throw => false,
            Op::Instanceof => false,
            Op::In => false,
            Op::ForInNext => false,
            Op::MakeClass => false,
            Op::GetProto => false,
            Op::CallThis => false,
            Op::ConstructThis => false,
            Op::CallThisArgs => false,
            Op::ConstructThisArgs => false,
            Op::GetIterator => false,
            Op::Yield => false,
            Op::GetAsyncIterator => false,
            Op::Await => false,
            Op::MakeRegexp => false,
            Op::SetGetterObj => false,
            Op::SetSetterObj => false,
            Op::SetGetterComputedObj => false,
            Op::SetSetterComputedObj => false,
            Op::GetPropLocal => false,
            Op::CloseUpvalues => false,
            Op::Inc => false,
            Op::Dec => false,
            Op::EnumKeys => false,
            Op::End => false,
        }
    }

    /// 是否为相对跳转指令。
    #[must_use]
    pub const fn is_jump(self) -> bool {
        match self {
            Op::Nop => false,
            Op::PushUndefined => false,
            Op::PushNull => false,
            Op::PushTrue => false,
            Op::PushFalse => false,
            Op::PushConst => false,
            Op::PushInt => false,
            Op::PushNegInt => false,
            Op::Pop => false,
            Op::Dup => false,
            Op::Swap => false,
            Op::LoadLocal => false,
            Op::StoreLocal => false,
            Op::LoadGlobal => false,
            Op::StoreGlobal => false,
            Op::LoadUpvalue => false,
            Op::StoreUpvalue => false,
            Op::MakeClosure => false,
            Op::Add => false,
            Op::Sub => false,
            Op::Mul => false,
            Op::Div => false,
            Op::Mod => false,
            Op::Pow => false,
            Op::BitAnd => false,
            Op::BitOr => false,
            Op::BitXor => false,
            Op::Shl => false,
            Op::Shr => false,
            Op::UShr => false,
            Op::Neg => false,
            Op::Not => false,
            Op::BitNot => false,
            Op::Typeof => false,
            Op::Eq => false,
            Op::StrictEq => false,
            Op::StrictNe => false,
            Op::Ne => false,
            Op::Lt => false,
            Op::Le => false,
            Op::Gt => false,
            Op::Ge => false,
            Op::Jmp => true,
            Op::JmpTruePop => true,
            Op::JmpFalsePop => true,
            Op::JmpTrueKeep => true,
            Op::JmpFalseKeep => true,
            Op::JmpNullishKeep => true,
            Op::OptionalJump => true,
            Op::Call => false,
            Op::CallMethod => false,
            Op::CallWithThis => false,
            Op::CallWithThisArgs => false,
            Op::New => false,
            Op::Return => false,
            Op::ReturnUndef => false,
            Op::NewObject => false,
            Op::NewArray => false,
            Op::GetProp => false,
            Op::SetProp => false,
            Op::SetPropObj => false,
            Op::SetPropTop => false,
            Op::GetElem => false,
            Op::SetElem => false,
            Op::SetElemTop => false,
            Op::DelProp => false,
            Op::DelElem => false,
            Op::SetPropComputedObj => false,
            Op::BuildArray => false,
            Op::ArrayPush => false,
            Op::ArraySpread => false,
            Op::CallArgs => false,
            Op::CallMethodArgs => false,
            Op::NewArgs => false,
            Op::SpreadObject => false,
            Op::UnaryPlus => false,
            Op::TypeofGlobal => false,
            Op::TryEnter => false,
            Op::TryExit => false,
            Op::TryExitFinally => false,
            Op::TryExitJmp => true,
            Op::Throw => false,
            Op::Instanceof => false,
            Op::In => false,
            Op::ForInNext => true,
            Op::MakeClass => false,
            Op::GetProto => false,
            Op::CallThis => false,
            Op::ConstructThis => false,
            Op::CallThisArgs => false,
            Op::ConstructThisArgs => false,
            Op::GetIterator => false,
            Op::Yield => false,
            Op::GetAsyncIterator => false,
            Op::Await => false,
            Op::MakeRegexp => false,
            Op::SetGetterObj => false,
            Op::SetSetterObj => false,
            Op::SetGetterComputedObj => false,
            Op::SetSetterComputedObj => false,
            Op::GetPropLocal => false,
            Op::CloseUpvalues => false,
            Op::Inc => false,
            Op::Dec => false,
            Op::EnumKeys => false,
            Op::End => false,
        }
    }

    /// 是否为控制流终结指令（其后顺序指令不可达）。
    #[must_use]
    pub const fn is_terminal(self) -> bool {
        match self {
            Op::Nop => false,
            Op::PushUndefined => false,
            Op::PushNull => false,
            Op::PushTrue => false,
            Op::PushFalse => false,
            Op::PushConst => false,
            Op::PushInt => false,
            Op::PushNegInt => false,
            Op::Pop => false,
            Op::Dup => false,
            Op::Swap => false,
            Op::LoadLocal => false,
            Op::StoreLocal => false,
            Op::LoadGlobal => false,
            Op::StoreGlobal => false,
            Op::LoadUpvalue => false,
            Op::StoreUpvalue => false,
            Op::MakeClosure => false,
            Op::Add => false,
            Op::Sub => false,
            Op::Mul => false,
            Op::Div => false,
            Op::Mod => false,
            Op::Pow => false,
            Op::BitAnd => false,
            Op::BitOr => false,
            Op::BitXor => false,
            Op::Shl => false,
            Op::Shr => false,
            Op::UShr => false,
            Op::Neg => false,
            Op::Not => false,
            Op::BitNot => false,
            Op::Typeof => false,
            Op::Eq => false,
            Op::StrictEq => false,
            Op::StrictNe => false,
            Op::Ne => false,
            Op::Lt => false,
            Op::Le => false,
            Op::Gt => false,
            Op::Ge => false,
            Op::Jmp => false,
            Op::JmpTruePop => false,
            Op::JmpFalsePop => false,
            Op::JmpTrueKeep => false,
            Op::JmpFalseKeep => false,
            Op::JmpNullishKeep => false,
            Op::OptionalJump => false,
            Op::Call => false,
            Op::CallMethod => false,
            Op::CallWithThis => false,
            Op::CallWithThisArgs => false,
            Op::New => false,
            Op::Return => true,
            Op::ReturnUndef => true,
            Op::NewObject => false,
            Op::NewArray => false,
            Op::GetProp => false,
            Op::SetProp => false,
            Op::SetPropObj => false,
            Op::SetPropTop => false,
            Op::GetElem => false,
            Op::SetElem => false,
            Op::SetElemTop => false,
            Op::DelProp => false,
            Op::DelElem => false,
            Op::SetPropComputedObj => false,
            Op::BuildArray => false,
            Op::ArrayPush => false,
            Op::ArraySpread => false,
            Op::CallArgs => false,
            Op::CallMethodArgs => false,
            Op::NewArgs => false,
            Op::SpreadObject => false,
            Op::UnaryPlus => false,
            Op::TypeofGlobal => false,
            Op::TryEnter => false,
            Op::TryExit => false,
            Op::TryExitFinally => false,
            Op::TryExitJmp => false,
            Op::Throw => true,
            Op::Instanceof => false,
            Op::In => false,
            Op::ForInNext => false,
            Op::MakeClass => false,
            Op::GetProto => false,
            Op::CallThis => false,
            Op::ConstructThis => false,
            Op::CallThisArgs => false,
            Op::ConstructThisArgs => false,
            Op::GetIterator => false,
            Op::Yield => false,
            Op::GetAsyncIterator => false,
            Op::Await => false,
            Op::MakeRegexp => false,
            Op::SetGetterObj => false,
            Op::SetSetterObj => false,
            Op::SetGetterComputedObj => false,
            Op::SetSetterComputedObj => false,
            Op::GetPropLocal => false,
            Op::CloseUpvalues => false,
            Op::Inc => false,
            Op::Dec => false,
            Op::EnumKeys => false,
            Op::End => false,
        }
    }
}

/// 一条指令：操作码 + 24 位操作数。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Instr {
    /// 操作码
    pub op: Op,
    /// 操作数（槽位号、立即值或常量池下标）
    pub operand: u32,
}

impl Instr {
    /// 构造一条指令。
    #[must_use]
    pub const fn new(op: Op, operand: u32) -> Self {
        Self { op, operand }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn opcodes_roundtrip_all_106_variants() {
        for b in 0..=105u8 {
            let op = Op::from_opcode(b).expect("必须成功解码有效操作码");
            assert_eq!(op.opcode(), b);
        }
        assert_eq!(Op::from_opcode(106), None);
        assert_eq!(Op::from_opcode(255), None);
    }

    #[test]
    fn stack_effects_balance_a_simple_addition() {
        let code = [
            Instr::new(Op::PushInt, 1),
            Instr::new(Op::PushInt, 2),
            Instr::new(Op::Add, 0),
        ];
        let depth: i32 = code.iter().map(|instr| instr.op.stack_effect()).sum();
        assert_eq!(depth, 1);
    }

    #[test]
    fn return_consumes_its_value() {
        assert_eq!(Op::Return.stack_effect(), -1);
    }

    #[test]
    fn meta_properties_integrity() {
        assert!(Op::PushUndefined.is_pure_push());
        assert!(Op::Jmp.is_jump());
        assert!(Op::Return.is_terminal());
        assert_eq!(Op::GetPropLocal.operand_kind(), OperandKind::PackedSlotName);
        assert_eq!(Op::CallMethod.operand_kind(), OperandKind::PackedCall);
        assert_eq!(Op::End.opcode(), 105);
    }
}
