const fs = require('node:fs');
const { X509Certificate } = require('node:crypto');
const pem = fs.readFileSync('test_cert.pem', 'utf8');
const cert = new X509Certificate(pem);
console.log('s1:', cert.subject);
console.log('s2:', cert.issuer);
console.log('s3:', cert.validFrom);
console.log('s4:', cert.validTo);
console.log('s5:', cert.serialNumber);
console.log('s6:', cert.fingerprint);
console.log('s7:', cert.fingerprint256);
console.log('s8:', cert.fingerprint512);
console.log('s9:', cert.ca);
console.log('s10:', cert.raw.length);
console.log('s11:', cert.toString().startsWith('-----BEGIN CERTIFICATE-----'));
console.log('s12:', cert.checkHost('example.com'));
console.log('s13:', cert.checkHost('www.example.com'));
console.log('s14:', cert.checkHost('other.com'));
console.log('s15:', JSON.stringify(cert.subjectAltName));
console.log('s16:', JSON.stringify(cert.keyUsage));
console.log('s17:', typeof cert.publicKey);
const keyPem = fs.readFileSync('test_key.pem', 'utf8');
const { createPrivateKey } = require('node:crypto');
console.log('s18:', cert.checkPrivateKey(createPrivateKey(keyPem)));
const der = Buffer.from(pem.replace(/-----BEGIN CERTIFICATE-----|-----END CERTIFICATE-----|\n/g, ''), 'base64');
const cert2 = new X509Certificate(der);
console.log('s19:', cert2.serialNumber === cert.serialNumber);
console.log('s20:', cert.validFrom.length, cert.validTo.length);
